### SimpleNPC Configuration File ###
# Author: @brokiem (github.com/brokiem)
# Source code: https://github.com/brokiem/SimpleNPC/

# Don't edit this version
config-version: 3
# ---------------------- #

# Enable npc look to players
# Default: true
enable-look-to-players: true
# Max npc distance to look at players
# Default: 8
max-look-distance: 8

# Enable command cooldown
# Default: true
enable-command-cooldown: true
# Coldown executing command when hit the NPC
# Default: 2.0 (float)
commandExecuteColdown: 1.0